apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: legacy-auth-gateway
  annotations:
    github.com/project-slug: dcohen213/legacy-auth-gateway
spec:
  type: other
  lifecycle: unknown
  owner: rhdh-team
